### ISSUE TITLE
Bundle lrelease tool with Slicer core

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerLanguagePacks#1]
Crowdin and the https://github.com/Slicer/SlicerLanguageTranslations repository stores .ts files. These .ts files must be converted to .qm files so that Slicer can use them. Qt toolkit's `lrelease` can do this conversion.

`lrelease` currently has to be installed by the user as part of Qt, but Qt is big and installation requires registration. To make the user experience simpler, `lrelease` should come in the Slicer installation package the same way as the Qt designer. Then users would not need to install Qt.

**Comment by lassoan** [comment]
@rkikinis wanted to try this extension and it took a day to get Qt/lrelease on his computer. This is probably a blocking issue for most users.

@mhdiop Would you be able to work on this?

**Comment by mhdiop** [comment]
Alright, I'm going to tackle this problem.

Regards.

Le ven. 11 nov. 2022 à 00:06, Andras Lasso ***@***.***> a
écrit :

**Comment by lassoan** [comment]
@jcfr just sent an email that he might be able to work on this and squeeze it into the upcoming 5.2 stable release.

@jcfr please let us know if you indeed can work on it or if @mhdiop should start digging into it. Thank you!

**Comment by jcfr** [comment]
I will likely follow up tomorrow with a pull request against this repository to have the Qt tools packages along side the language tool module. This will allow us to further tweaks and address issues after 5.2 is out.

**Comment by lassoan** [comment]
Why not adding it to the Slicer package the same way as Qt designer?

**Comment by mhdiop** [comment]
Ok @lassoan, no problem.

I see that @jcfr has already started working on it. I will therefore continue to work on the tasks that were previously assigned to me.

Thanks to both of you.

**Comment by lassoan** [comment]
This feature is now implemented - ready to be tested on Slicer Preview Releases downloaded on 2023-01-27 or later.

**Comment by lassoan** [comment]
Tested on Windows with latest Slicer Preview Release and it works well.
