### ISSUE TITLE
HTML tags and special characters get corrupted

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerLanguagePacks#14]
Weblate corrupts translated text that contain HTML tags (e.g., in formatted text) and special characters (e.g., in menus `&` is replaced by `&amp;`).

This is most likely due to Weblate rewriting text to be "safe html". Unfortunately, this essentially corrupts the text.

**Comment by lassoan** [comment]
It makes sense not to use complex HTML formatting in translatable text, as there is a high chance that translators accidentally modify the HTML code. Therefore instead of disabling HTML sanitization should not be necessary to address this issue.

However, rewriting of `&` character to `&amp;` would break all the hotkey assignments in all menus and buttons (e.g., [`&Edit`](https://hosted.weblate.org/translate/3d-slicer/3d-slicer/en/?offset=1&q=%26Edit&sort_by=-priority%2Cposition&checksum=) makes `Alt`+`E` a hotkey for `Edit`). Unfortunately, Weblate developers do not have the resources to fix this issue (see https://github.com/WeblateOrg/weblate/issues/6490), and disabling would be very error-prone (translators would forget to manually adjust the flag). This justifies disabling of sanitization feature in Weblate for the whole Slicer project.

**Comment by lassoan** [comment]
See more information on unsafe html: https://docs.weblate.org/en/latest/user/checks.html#unsafe-html
Description of how to disable it for a component: https://docs.weblate.org/en/latest/admin/checks.html#custom-checks

How it was specified for 3d-slicer component at https://hosted.weblate.org/settings/3d-slicer/3d-slicer/#translation:

![image](https://user-images.githubusercontent.com/307929/196724230-0e61e500-2026-4c95-9805-e4b421a940f4.png)

I've removed this `safe-html` flag now.

I've also replaced a handful of occurrences of special characters in existing translations, but someone would need to complete this task. Replacements that needs to be done:
- `&lt;` -> `<`
- `&gt;` -> `>`
- `&amp;` -> `&`

**Comment by DDinghoya** [comment]
Great! Thank you for your strong support! :)

**Comment by lassoan** [comment]
disabling safe-html fixed the issue
