### ISSUE TITLE
Trouble entering to Add DICOM data module

### ISSUE THREAD

**Issue by MohamedAllali** [Slicer/SlicerLanguagePacks#20]
I have a problem entering the Add DICOM data module whenever I try to enter it, I drown the program, I don’t know why and this only happens in the Arabic version. this happened after I translated this module into Arabic in weblate.

**Comment by MohamedAllali** [comment]
I used three versions of slicer :
Slicer 5.3.0 - 2023-03-11
Slicer 5.3.0 - 2023-03-15
Slicer 5.3.0 - 2023-03-27
and I get the same problem

**Comment by lassoan** [comment]
Everything will work correctly again in the Slicer Preview Release that you download tomorrow after 12pm EST. See more details here: https://github.com/Slicer/SlicerLanguagePacks/issues/26

**Comment by MohamedAllali** [comment]
Well thanks for letting me know.

Mohamed.

Le mer. 12 avr. 2023 à 17:07, Andras Lasso ***@***.***> a
écrit :
