### ISSUE TITLE
DICOM module is not yet fully translated into French Slicer version 5.3.0 2023-04-05

### ISSUE THREAD

**Issue by Papa96108** [Slicer/SlicerLanguagePacks#23]
Their following screenshoots show part of the DICOM module which are not translated

- [x] Reload and test section
- [x] A part of the table shoowing patient data information  

![1](https://user-images.githubusercontent.com/78362404/230608552-3e569fbb-020d-41dc-a8ba-df2eb782f852.png)

- [x] some words of this list of option button 
- [x] "Data Probe"

![2](https://user-images.githubusercontent.com/78362404/230609148-2db036b8-6951-47d6-acfa-b7c55147e22f.png)

- [x] Description text of preset's button mentioned above is not translated in French => now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/43

![3](https://user-images.githubusercontent.com/78362404/230609370-22fdd054-4106-45e8-b4f0-bb4db4627b31.png)

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/105887351/d487ae39-a2ad-48ef-b904-9dbc3472b0b6)

- [x] The "Propriétés du volume" and "Propriétés du label" section 

![4](https://user-images.githubusercontent.com/78362404/230609711-0e060989-ebdb-48a7-8fa6-d5f6a15f2943.png)

- [x] These underlined words must be translated into French and updated in the [DICOM tutorial](https://docs.google.com/presentation/d/10YGDKNhV4er0PsmGlxg0xzg9cPoS0OfO/edit#slide=id.g22f0a235bdf_3_40) -> this is now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/63

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/105887351/17c6dd3c-0afb-4537-a804-a8432dad5e87)

**Comment by lassoan** [comment]
- "Reload and test" section is only for developers - it will remain in English.
- "Data Probe" is from Python scripted module. We are still working on the infrastructure that enables Python module translation. See https://github.com/Slicer/SlicerLanguagePacks/issues/8
- Presets are defined in logic classes. They cannot be translated yet. See https://github.com/Slicer/Slicer/issues/6647

Everything else should be translatable in Slicer Preview Releases downloaded on 2023-04-12 at 12pm EST or later.

**Comment by spujol** [comment]
Tests with Slicer5.3.0-2023-04-17 on Windows:

The elements below remain untranslated:

DICOM module:
- Help section ("For more information see the online documentation")
- Load button 
- Messages displayed in pop-up windows during DICOM data loading
- Names of DICOM Plugins

Volumes module:
- Presets

**Comment by mhdiop** [comment]
Thanks Sonia for pointing out those untranslated strings.

They are taken into account in the [recently merged commit](https://github.com/Slicer/Slicer/commit/60c659f33b672d8e8a7193f0741a2f56aaac080c).

Regards.

**Comment by FatouBintou22** [comment]
April 25 tests with Slicer5.3.0-2023-04-23 on Windows:

The elements below are not available on weblate:

**Show Zoomed Slice** in Data probe
**Segment this..** in right click/node/add DICOM data
**Compositing with shading, Max/min intensity projection** in Technique/Advanced/Volume Rendering
The text content of **help, acknowledgments** in Volume Rendering, Segmentations, Models
**Export to new label map** in export/import models and annotations/Segmentations
**Create new table** in Segment Statistics
**Labelmap Statistics, Scalar Volume Statistics, Closed Surface Statistics** in Advanced/Segment Statistics
**Attribute name, Attribute value** in MRML/Data Node Information (translated in weblate)
**Scalar** in Volume Types/Volume Information/Volumes
**Filter color** in Lookup Table/Display/Volumes
Segmentation tools (**Draw, Paint, Erase,** ..) in Segment Editor

**Comment by FatouBintou22** [comment]
- [ ] Description text of preset's button mentioned above is not translated in French

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/105887351/d487ae39-a2ad-48ef-b904-9dbc3472b0b6)

- [ ] These underlined words must be translated into French and updated in the [DICOM tutorial](https://docs.google.com/presentation/d/10YGDKNhV4er0PsmGlxg0xzg9cPoS0OfO/edit#slide=id.g22f0a235bdf_3_40)

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/105887351/17c6dd3c-0afb-4537-a804-a8432dad5e87)

**Comment by lassoan** [comment]
All issues are fixed or tracked elsewhere.
