### ISSUE TITLE
French version of Slicer DICOM module crashes

### ISSUE THREAD

**Issue by spujol** [Slicer/SlicerLanguagePacks#26]
The French version of Slicer crashes when accessing the Add DICOM data module.

Slicer 5.3.0.2023-04.10 on Mac OSX 12.6

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libCTKWidgets.0.1.dylib       	       0x10f503f79 ctkModalityWidget::setVisibleModalities(QStringList const&) + 745
1   libCTKWidgets.0.1.dylib       	       0x10f5021a8 ctkModalityWidgetPrivate::init() + 648
2   libCTKWidgets.0.1.dylib       	       0x10f504495 ctkModalityWidget::ctkModalityWidget(QWidget*) + 85
3   libCTKDICOMWidgets.0.1.dylib  	       0x10ec40983 Ui_ctkDICOMQueryWidget::setupUi(QWidget*) + 3043
4   libCTKDICOMWidgets.0.1.dylib  	       0x10ec3fb3f ctkDICOMQueryWidget::ctkDICOMQueryWidget(QWidget*) + 127
5   libCTKDICOMWidgets.0.1.dylib  	       0x10ec3b136 Ui_ctkDICOMQueryRetrieveWidget::setupUi(QWidget*) + 1142
6   libCTKDICOMWidgets.0.1.dylib  	       0x10ec3aba0 ctkDICOMQueryRetrieveWidgetPrivate::init() + 32
7   libCTKDICOMWidgets.0.1.dylib  	       0x10ec3b665 ctkDICOMQueryRetrieveWidget::ctkDICOMQueryRetrieveWidget(QWidget*) + 85
8   libCTKDICOMWidgets.0.1.dylib  	       0x10ec24218 ctkDICOMBrowserPrivate::init() + 824
9   libCTKDICOMWidgets.0.1.dylib  	       0x10ec2600b ctkDICOMBrowser::ctkDICOMBrowser(QSharedPointer<ctkDICOMDatabase>, QWidget*) + 171
10  libqSlicerBaseQTGUI.dylib     	       0x10ee3c697 qSlicerApplication::createDICOMBrowserForMainDatabase() + 55
11  libqSlicerBaseQTGUI.dylib     	       0x10eec5fb0 qSlicerApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 1328
12  libqSlicerBaseQTGUI.dylib     	       0x10eec633e qSlicerApplication::qt_metacall(QMetaObject::Call, int, void**) + 62
13  libPythonQt.dylib             	       0x1138e9fdf PythonQtCallSlot(PythonQtClassInfo*, QObject*, _object*, bool, PythonQtSlotInfo*, void*, _object**, void**, PythonQtPassThisOwnershipType*) + 799
14  libPythonQt.dylib             	       0x1138eb7c1 PythonQtSlotFunction_CallImpl(PythonQtClassInfo*, QObject*, PythonQtSlotInfo*, _object*, _object*, void*, void**, PythonQtPassThisOwnershipType*) + 1633
15  libPythonQt.dylib             	       0x1138ea8dd PythonQtMemberFunction_Call(PythonQtSlotInfo*, _object*, _object*, _object*) + 189
16  libpython3.9.dylib            	       0x119d9a0c8 _PyObject_MakeTpCall + 376
17  libpython3.9.dylib            	       0x119e9e572 call_function + 626
18  libpython3.9.dylib            	       0x119e9ae04 _PyEval_EvalFrameDefault + 25572
19  libpython3.9.dylib            	       0x119e9f188 _PyEval_EvalCode + 2360
20  libpython3.9.dylib            	       0x119d9a7a9 _PyFunction_Vectorcall + 265
21  libpython3.9.dylib            	       0x119d99ef4 _PyObject_FastCallDictTstate + 260
22  libpython3.9.dylib            	       0x119d9ab8b _PyObject_Call_Prepend + 139
23  libpython3.9.dylib            	       0x119e05cd4 slot_tp_init + 100
24  libpython3.9.dylib            	       0x119dfdf04 type_call + 340
25  libpython3.9.dylib            	       0x119d9a0c8 _PyObject_MakeTpCall + 376
26  libpython3.9.dylib            	       0x119e9e572 call_function + 626
27  libpython3.9.dylib            	       0x119e9ae04 _PyEval_EvalFrameDefault + 25572
28  libpython3.9.dylib            	       0x119d9a8b3 function_code_fastcall + 163
29  libpython3.9.dylib            	       0x119dacd7d method_vectorcall + 365
30  libpython3.9.dylib            	       0x119d9aa53 PyObject_CallObject + 131
31  libqSlicerBaseQTCore.dylib    	       0x10f730883 qSlicerPythonCppAPI::callMethod(int, _object*) + 243
32  libqSlicerBaseQTCore.dylib    	       0x10f6c806f qSlicerAbstractCoreModule::createNewWidgetRepresentation() + 63
33  libqSlicerBaseQTCore.dylib    	       0x10f6c801f qSlicerAbstractCoreModule::widgetRepresentation() + 31
34  libqSlicerBaseQTGUI.dylib     	       0x10ee6a97f qSlicerModulePanel::addModule(qSlicerAbstractCoreModule*) + 31
35  libqSlicerBaseQTGUI.dylib     	       0x10ee6a5fd qSlicerModulePanel::setModule(QString const&) + 269
36  QtCore                        	       0x1117671bc 0x11154c000 + 2208188
37  libqSlicerBaseQTGUI.dylib     	       0x10eecbe64 qSlicerModuleSelectorToolBar::moduleSelected(QString const&) + 52
38  libqSlicerBaseQTGUI.dylib     	       0x10ee6e38a qSlicerModuleSelectorToolBar::actionSelected(QAction*) + 1418
39  QtCore                        	       0x1117671bc 0x11154c000 + 2208188
40  libqSlicerBaseQTGUI.dylib     	       0x10eecb834 qSlicerModulesMenu::currentModuleChanged(QString const&) + 52
41  libqSlicerBaseQTGUI.dylib     	       0x10ee69d82 qSlicerModulesMenu::actionSelected(QAction*) + 114
42  QtCore                        	       0x1117671bc 0x11154c000 + 2208188
43  QtWidgets                     	       0x10fd79ff6 QAction::activate(QAction::ActionEvent) + 310
44  libqSlicerBaseQTGUI.dylib     	       0x10ee69c74 qSlicerModulesMenu::setCurrentModule(QString const&) + 84
45  QtCore                        	       0x1117671bc 0x11154c000 + 2208188
46  libqSlicerBaseQTGUI.dylib     	       0x10eec9c04 qSlicerLayoutManager::selectModule(QString const&) + 52
47  libqSlicerWelcomeModule.dylib 	       0x14bae68dd qSlicerWelcomeModuleWidgetPrivate::selectModule(QString const&) + 93
48  libqSlicerWelcomeModule.dylib 	       0x14bae7fab qSlicerWelcomeModuleWidget::loadDicomData() + 43
49  libqSlicerWelcomeModule.dylib 	       0x14bae93de qSlicerWelcomeModuleWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 62
50  QtCore                        	       0x1117671bc 0x11154c000 + 2208188
51  QtWidgets                     	       0x10fe6ddcf 0x10fd73000 + 1027535
52  QtWidgets                     	       0x10fe6dc49 0x10fd73000 + 1027145
53  QtWidgets                     	       0x10fe6edee QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 270
54  QtWidgets                     	       0x10fdbf11b QWidget::event(QEvent*) + 443
55  QtWidgets                     	       0x10ff17286 QPushButton::event(QEvent*) + 86
56  QtWidgets                     	       0x10fd83526 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
57  QtWidgets                     	       0x10fd861d4 QApplication::notify(QObject*, QEvent*) + 6916
58  libqSlicerBaseQTGUI.dylib     	       0x10ee36df4 qSlicerApplication::notify(QObject*, QEvent*) + 20
59  QtCore                        	       0x111735b17 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
60  QtWidgets                     	       0x10fd83e22 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 882
61  QtWidgets                     	       0x10fdddffe 0x10fd73000 + 438270
62  QtWidgets                     	       0x10fddc78f 0x10fd73000 + 432015
63  QtWidgets                     	       0x10fd83526 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
64  QtWidgets                     	       0x10fd848ad QApplication::notify(QObject*, QEvent*) + 477
65  libqSlicerBaseQTGUI.dylib     	       0x10ee36df4 qSlicerApplication::notify(QObject*, QEvent*) + 20
66  QtCore                        	       0x111735b17 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
67  QtGui                         	       0x110967fbc QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3500
68  QtGui                         	       0x1109678bd QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 1709
69  QtGui                         	       0x11094df7c QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 204
70  libqcocoa.dylib               	       0x12658f7f8 0x126555000 + 239608
71  CoreFoundation                	    0x7ff80c87817b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
72  CoreFoundation                	    0x7ff80c8780e3 __CFRunLoopDoSource0 + 180
73  CoreFoundation                	    0x7ff80c877e5d __CFRunLoopDoSources0 + 242
74  CoreFoundation                	    0x7ff80c876878 __CFRunLoopRun + 892
75  CoreFoundation                	    0x7ff80c875e3c CFRunLoopRunSpecific + 562
76  HIToolbox                     	    0x7ff8155255e6 RunCurrentEventLoopInMode + 292
77  HIToolbox                     	    0x7ff815525213 ReceiveNextEventCommon + 283
78  HIToolbox                     	    0x7ff8155250e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
79  AppKit                        	    0x7ff80f2affad _DPSNextEvent + 927
80  AppKit                        	    0x7ff80f2ae66a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
81  AppKit                        	    0x7ff80f2a0d19 -[NSApplication run] + 586
82  libqcocoa.dylib               	       0x12658e4d3 0x126555000 + 234707
83  QtCore                        	       0x1117320e6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 502
84  QtCore                        	       0x1117360b2 QCoreApplication::exec() + 130
85  libqSlicerBaseQTCore.dylib    	       0x10f6dc969 qSlicerCoreApplication::exec() + 9
86  Slicer                        	       0x10e69fb48 main + 488
87  dyld                          	       0x11c99452e start + 462

**Comment by lassoan** [comment]
Thanks for reporting, we [fixed the issue yesterday](https://github.com/commontk/CTK/pull/1080), and it will be available in the Slicer Preview Release from tomorrow.

Unfortunately, there won't be any fix in the Slicer Stable Release (Slicer-5.2.2). To fix that, I'll undo the translation of imaging modality codes (XA, RF, RTSTRUCT, CT, ...) in the DICOM query/retrieve widget for now.

**Comment by pieper** [comment]
Thanks @jcfr, but I think this will be a transient issue as the translation work is ongoing but it should settle out.  For now having the translations work only on the Preview versions is going to work for now since other small issues may crop up.

**Comment by lassoan** [comment]
I've implemented a patch step in the language pack installation process that forces the original English text for all the modality codes for Slicer-5.2. Many strings in CTK were not translatable in Slicer-5.2 anyway, so this should not be a problem at all (only the application crash was an issue).

When Slicer-5.4 is planned for?
