### ISSUE TITLE
Update English documentation and screenshot to match the latest version of the software

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerLanguagePacks#27]
Update [this page](https://github.com/Slicer/SlicerLanguagePacks/blob/main/HowToUse.md), including screenshots to match the current software version.

**Comment by MohamedAllali** [comment]
Got it, thanks!

Le mer. 17 mai 2023 à 12:45, Andras Lasso ***@***.***> a
écrit :

**Comment by MohamedAllali** [comment]
Good evening, Mr. Andras

I hope everything is going well. I want to ask you a question related to
SlicerLanguagePacks update, isn't it that Qt toolkit is now integrated with
SlicerLanguagePacks, so there is no need to download and install, my
question to you is it better to delete the download and install Qt toolkit
part of HowToUse
<https://github.com/Slicer/SlicerLanguagePacks/blob/main/HowToUse.md#:~:text=this%20language%20selector.-,Download%20and%20install%20Qt%20toolkit,is%20done%2C%20the%20lrelease%20file%20will%20be%20located%20in%20%22/usr/bin/%22%20.,-SlicerLanguagePacks/HowToUse.md>
.

**Comment by MohamedAllali** [comment]
Ok, thanks for the clarification.
Happy Weekend.

Mohamed.

Le sam. 20 mai 2023 à 14:15, Andras Lasso ***@***.***> a
écrit :

**Comment by MohamedAllali** [comment]
@lassoan I've updated How to use, you can see from [here](https://github.com/Slicer/SlicerLanguagePacks/blob/main/HowToUse.md), wait for your comment if there's anything that needs to be modified.

**Comment by lassoan** [comment]
done
