### ISSUE TITLE
String context changes at runtime deny some translations to work

### ISSUE THREAD

**Issue by mhdiop** [Slicer/SlicerLanguagePacks#52]
# Concerned strings (in DICOM module)

## The "Segment this" option

<img width="953" alt="image" src="https://github.com/Slicer/SlicerLanguagePacks/assets/103750673/7504188a-9f93-4c2b-8a39-614a810b0582">

## The "Calculate statistics" option

This text will show up after the "Segment this..." option has been chosen.

<img width="959" alt="image" src="https://github.com/Slicer/SlicerLanguagePacks/assets/103750673/25902e0d-6b79-45de-9e47-024d1c115fb9">

# Cause of the problem

First, those strings are already marked and translated. After investigation, I realized that the problem comes from a change in the string context (context at extraction time differs from the one at runtime). In fact, the `__init.py__` file added in the runtime folder (see the following pictures) changes the string context from `SegmentEditorSubjectHierarchyPlugin` to `SubjectHierarchyPlugins.SegmentEditorSubjectHierarchyPlugin`. What deny Slicer from getting the translated strings.

## Folder structure at extraction time

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/103750673/73d384f6-bb94-4884-8fe5-a85a7a612442)

## Folder structure at runtime

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/103750673/23d94f1c-d433-4af6-871d-f28f9325eaee)

# Possible solutions

I unfortunately don't have sufficient information about rules behind folder structure changes at runtime. However, the following solutions might work:

1. Add a dummy `__init.py__` file in the original source folder
2. For this specific file, use `translate` instead of the `_` function so that to directly specify the context
3. Update the translation function

To verify my hypothesis, I implemented a quick fix that resolves the current problem, using the 3<sup>rd</sup> option. However, I don't know if it takes all possible cases since, as said earlier, I don't have sufficient information about rules behind folder structure changes at runtime.

```py
# source file : Base/Python/slicer/i18n.py

def tr(text):
    filename = inspect.stack()[1][1]
    contextName = getContext(filename)
    translated = translate(contextName, text)
    if text == translated:
        index = contextName.find('.')
        if index != -1:
            return translate(contextName[index+1:], text)
    return translated
```

## Obtained result

<img width="959" alt="image" src="https://github.com/Slicer/SlicerLanguagePacks/assets/103750673/0a599f25-74e4-43f0-a231-e7f18d6830f9">

Thank you in advance, @lassoan and @pieper, for your suggestions.

**Comment by pieper** [comment]
Good research @mhdiop - I don't have a better solution off the top of my head.  Perhaps @lassoan will have an idea or if not we can discuss when we meet on Wednesday.

**Comment by mhdiop** [comment]
Thank you @pieper for your feedback. Ok, I'll wait for Andras' answer, or for the next meeting as suggested.

Best regards.

**Comment by lassoan** [comment]
I've run into the same issue with the Segment Editor effects. I ended up changing the source directory structure to match the installed directory structure. Consistency of the directory structure between source and install tree is generally desirable anyway.

**Comment by mhdiop** [comment]
Thank you @lassoan for your feedback. I'll explore that to see if it better matches this case.

Regards.
