### ISSUE TITLE
Ukrainian language

### ISSUE THREAD

**Issue by Ua-user** [Slicer/SlicerLanguagePacks#53]
Ukrainian language does nor work perfectly. 

It says "Download translations for 3d-slicer/uk...
Download translations for ctk/uk...
  Download failed. This component may not have been translated to the selected language.
Download translations for slicerigt/uk...
  Download failed. This component may not have been translated to the selected language."

Some items are transnlated, but not the entire interface. Is this package under construction? I may help to complete

**Comment by fedorov** [comment]
@Ua-user would you like to join forces working on Ukrainian translation? I know Ukrainian, but I do not know almost anything about Ukrainian terms used in medical imaging - I only worked with English on medical imaging applications.

**Comment by Ua-user** [comment]
Hi Andrey!

Yes, I would like to join. I am an MD PhD working on a research wich
involves 3DSlicer. I am from Ukraine and believe this is a fantastic
platform.

How should I start?

Vitaliy

ср, 22 лист. 2023 р., 15:43 користувач Andrey Fedorov <
***@***.***> пише:

**Comment by lassoan** [comment]
"Translation guidelines" in the LanguagePacks extension documentation is a good starting point: https://github.com/Slicer/SlicerLanguagePacks#documentation

**Comment by fedorov** [comment]
Vitaliy, I am happy to have a video call to discuss, go together over the steps and coordinate how to proceed - this might be more efficient. You are welcome to email me at the email below to coordinate!

<img width="254" alt="image" src="https://github.com/Slicer/SlicerLanguagePacks/assets/313942/c9a5054b-52a6-4a3c-9a29-4b4aa63905e7">
