### ISSUE TITLE
Tutorial Maker: Arrows directions

### ISSUE THREAD

**Issue by pauloebveiga** [Slicer/SlicerLanguagePacks#74]
Problem: limited arrow direction.

Description: to produce identical tutorials, we need more directional movement of the arrows, in addition to North, South, East and West.

@enriquehdez98 @DouSam @LuskasHusty

**Comment by DouSam** [comment]
Issues related to TutorialMaker should be opened at https://github.com/SlicerLatinAmerica/TutorialMaker/issues!
