### ISSUE TITLE
Develop infrastructure for Python scripted module translation

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerLanguagePacks#8]
- [x] Mark strings as translatable in one Python module
- [x] Implement `_()` function for one Python module

**Comment by lassoan** [comment]
I've tried how to extract strings marked with `_()` function in a Python file using `lupdate` in Qt 6.2:

```
c:\Qt6\6.2.4\msvc2019_64\bin\lupdate.exe c:\D\S4\Modules\Scripted\DataProbe\DataProbe.py -tr-function-alias tr=_ -ts test.ts
```

Example output .ts file:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message>
        <location filename="DataProbe.py" line="291"/>
        <source>Data Probe</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
```

I've found these limitations:
- `context` -> `name` is empty (`location` is extracted, but that is just additional information for the translator; it is not used for retrieving the translated string)
- f-strings are not supported (if I specify an f-string then lupdate ignores that text)

**Considering these limitations and the somewhat extra complication of getting Qt-6.2 in the near future, I think it is not worth it to use Qt's lupdate for extracting strings from .py files.**

Instead, we could use Python's `ast` package to parse Python files and detect occurrences of `_()` function calls (and other translation functions, such as [QT_TR_NOOP](https://doc.qt.io/qt-5/qtglobal.html#QT_TR_NOOP)). See an introduction tutorial of ast package [here](https://medium.com/@wshanshan/intro-to-python-ast-module-bbd22cd505f7).

To be consistent with translation of how it is done for QObject-based classes in C++. However, Python class names are not all in the same global namespace: the same classname can be used in many python modules. For example, all the scripted segment editor effects have the same name [`SegmentEditorEffect`](https://github.com/lassoan/SlicerSegmentEditorExtraEffects/blob/master/SegmentEditorDrawTube/SegmentEditorDrawTubeLib/SegmentEditorEffect.py) therefore that name would not work well. However, if we could included the python module name as well (such as `SegmentEditorDrawTubeLib.SegmentEditorEffect`) then that could work well.

This code could be used for getting the class module and name for translation: https://github.com/lassoan/Slicer/commit/f463e224cb3ad606eea688490884edb32e69182d

So, the only major missing part is the string extraction from .py files using ast.

**Comment by syrjay** [comment]
these are relevant details, all this is not yet supported with the lupdate of Qt6.2 since it is recent and it may not have been much experimented with .py files. So it would be a risk to try to work with lupdate for these files.
Currently I am looking at the ast library and then experimenting with test files.

**Comment by lassoan** [comment]
New repository is created https://github.com/Slicer/sliceri18n - further actions will be added as issues to that repository.

**Comment by lassoan** [comment]
done
