### ISSUE TITLE
How to reload the English version of Slicer

### ISSUE THREAD

**Issue by spujol** [Slicer/SlicerLanguagePacks#9]
I have selected fr-FR in the Weblate Languages selector menu of the Language Tools extension. When I restart the application, Slicer loads the modules translated to French (e.g. Models).

To switch back to the original English version of Slicer, I unselected fr-FR in the Language Tools extension. However, when I restart the application, Slicer re-loads the modules translated in French instead of the original modules in English although the language selected in the Language Tools module appears as 'None'.

I am using Slicer version 4.13-2022-04-27 on MacOS.

**Comment by lassoan** [comment]
LanguagePacks extension is for installing/updating additional languages. 

You can select the application language in menu: Edit -> Application settings -> General -> Language.

**Comment by spujol** [comment]
Thank you, we will have to add this to the Slicer internationalization tutorial.

**Comment by lassoan** [comment]
It is described here: https://github.com/Slicer/SlicerLanguagePacks#set-application-language

Feel free to edit the page to make it more clear.

**Comment by lassoan** [comment]
I've added an application language selector to the module GUI.
